from __future__ import annotations

BOT_SEEDS = [{'archetype': 'Macro and flows',
  'asset_universe': 'BTC,ETH',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'BTC, ETH',
  'horizon_label': '3 to 30 days',
  'name': 'Macro Narrative Bot',
  'risk_style': 'Measured conviction',
  'slug': 'macro-narrative',
  'thesis': 'Connects liquidity conditions, ETF flows, and policy signals to medium-term market positioning.'},
 {'archetype': 'Sentiment acceleration',
  'asset_universe': 'BTC,ETH,SOL',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'BTC, ETH, SOL',
  'horizon_label': '1 to 3 days',
  'name': 'Social Momentum Bot',
  'risk_style': 'Fast-following',
  'slug': 'social-momentum',
  'thesis': 'Looks for crowd acceleration where engagement velocity and spot structure reinforce one another.'},
 {'archetype': 'Technical structure',
  'asset_universe': 'BTC,ETH,SOL',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'Liquid majors',
  'horizon_label': 'Intraday to 3 days',
  'name': 'Breakout Bot',
  'risk_style': 'Momentum-biased',
  'slug': 'breakout',
  'thesis': 'Publishes when structure, participation, and volatility line up for continuation moves.'},
 {'archetype': 'Mean reversion',
  'asset_universe': 'BTC,ETH,SOL',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'Crowded narratives',
  'horizon_label': '1 to 7 days',
  'name': 'Contrarian Bot',
  'risk_style': 'Selective reversal',
  'slug': 'contrarian',
  'thesis': 'Fades consensus when sentiment, price extension, and positioning become one-sided.'},
 {'archetype': 'Cross-market risk',
  'asset_universe': 'BTC,ETH,SOL',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'Cross-market risk',
  'horizon_label': '1 to 14 days',
  'name': 'Risk Sentinel',
  'risk_style': 'Defensive',
  'slug': 'risk-sentinel',
  'thesis': 'Flags fragility, volatility expansion, and asymmetry deterioration before they hit the broader roster.'},
 {'archetype': 'Event response',
  'asset_universe': 'BTC,ETH,SOL',
  'created_at': '2026-04-01T08:00:00Z',
  'focus': 'News-sensitive majors',
  'horizon_label': 'Intraday to 1 day',
  'name': 'News Reaction Bot',
  'risk_style': 'Fast event trader',
  'slug': 'news-reaction',
  'thesis': 'Measures how efficiently markets absorb headlines and whether narrative follow-through is still available.'}]

MARKET_SNAPSHOT_SEEDS = [{'as_of': '2026-04-01T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.014,
  'price': 82500.0,
  'signal_bias': 0.35,
  'source': 'seed-market',
  'trend_score': 0.42,
  'volatility': 0.031,
  'volume_24h': 38100000000.0},
 {'as_of': '2026-04-02T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.009,
  'price': 83250.0,
  'signal_bias': 0.37,
  'source': 'seed-market',
  'trend_score': 0.45,
  'volatility': 0.033,
  'volume_24h': 38900000000.0},
 {'as_of': '2026-04-03T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.016,
  'price': 84600.0,
  'signal_bias': 0.41,
  'source': 'seed-market',
  'trend_score': 0.52,
  'volatility': 0.036,
  'volume_24h': 40700000000.0},
 {'as_of': '2026-04-04T00:00:00Z',
  'asset': 'BTC',
  'change_24h': -0.009,
  'price': 83800.0,
  'signal_bias': 0.08,
  'source': 'seed-market',
  'trend_score': 0.21,
  'volatility': 0.041,
  'volume_24h': 39500000000.0},
 {'as_of': '2026-04-05T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.017,
  'price': 85220.0,
  'signal_bias': 0.32,
  'source': 'seed-market',
  'trend_score': 0.48,
  'volatility': 0.039,
  'volume_24h': 42100000000.0},
 {'as_of': '2026-04-06T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.014,
  'price': 86410.0,
  'signal_bias': 0.43,
  'source': 'seed-market',
  'trend_score': 0.55,
  'volatility': 0.037,
  'volume_24h': 43800000000.0},
 {'as_of': '2026-04-07T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.009,
  'price': 87200.0,
  'signal_bias': 0.47,
  'source': 'seed-market',
  'trend_score': 0.59,
  'volatility': 0.034,
  'volume_24h': 44700000000.0},
 {'as_of': '2026-04-08T00:00:00Z',
  'asset': 'BTC',
  'change_24h': 0.017,
  'price': 88640.0,
  'signal_bias': 0.5,
  'source': 'seed-market',
  'trend_score': 0.62,
  'volatility': 0.035,
  'volume_24h': 46300000000.0},
 {'as_of': '2026-04-01T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.011,
  'price': 1810.0,
  'signal_bias': 0.29,
  'source': 'seed-market',
  'trend_score': 0.38,
  'volatility': 0.038,
  'volume_24h': 14500000000.0},
 {'as_of': '2026-04-02T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.019,
  'price': 1845.0,
  'signal_bias': 0.35,
  'source': 'seed-market',
  'trend_score': 0.43,
  'volatility': 0.04,
  'volume_24h': 14900000000.0},
 {'as_of': '2026-04-03T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.012,
  'price': 1868.0,
  'signal_bias': 0.4,
  'source': 'seed-market',
  'trend_score': 0.47,
  'volatility': 0.039,
  'volume_24h': 15200000000.0},
 {'as_of': '2026-04-04T00:00:00Z',
  'asset': 'ETH',
  'change_24h': -0.009,
  'price': 1852.0,
  'signal_bias': 0.03,
  'source': 'seed-market',
  'trend_score': 0.19,
  'volatility': 0.042,
  'volume_24h': 15000000000.0},
 {'as_of': '2026-04-05T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.018,
  'price': 1886.0,
  'signal_bias': 0.31,
  'source': 'seed-market',
  'trend_score': 0.44,
  'volatility': 0.041,
  'volume_24h': 15700000000.0},
 {'as_of': '2026-04-06T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.015,
  'price': 1914.0,
  'signal_bias': 0.42,
  'source': 'seed-market',
  'trend_score': 0.49,
  'volatility': 0.043,
  'volume_24h': 16200000000.0},
 {'as_of': '2026-04-07T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.018,
  'price': 1948.0,
  'signal_bias': 0.48,
  'source': 'seed-market',
  'trend_score': 0.56,
  'volatility': 0.04,
  'volume_24h': 16800000000.0},
 {'as_of': '2026-04-08T00:00:00Z',
  'asset': 'ETH',
  'change_24h': 0.017,
  'price': 1982.0,
  'signal_bias': 0.52,
  'source': 'seed-market',
  'trend_score': 0.6,
  'volatility': 0.039,
  'volume_24h': 17300000000.0},
 {'as_of': '2026-04-01T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.017,
  'price': 118.0,
  'signal_bias': 0.39,
  'source': 'seed-market',
  'trend_score': 0.46,
  'volatility': 0.057,
  'volume_24h': 4600000000.0},
 {'as_of': '2026-04-02T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.025,
  'price': 121.0,
  'signal_bias': 0.44,
  'source': 'seed-market',
  'trend_score': 0.52,
  'volatility': 0.061,
  'volume_24h': 4750000000.0},
 {'as_of': '2026-04-03T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.025,
  'price': 124.0,
  'signal_bias': 0.49,
  'source': 'seed-market',
  'trend_score': 0.57,
  'volatility': 0.063,
  'volume_24h': 4890000000.0},
 {'as_of': '2026-04-04T00:00:00Z',
  'asset': 'SOL',
  'change_24h': -0.008,
  'price': 123.0,
  'signal_bias': 0.1,
  'source': 'seed-market',
  'trend_score': 0.24,
  'volatility': 0.066,
  'volume_24h': 4820000000.0},
 {'as_of': '2026-04-05T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.024,
  'price': 126.0,
  'signal_bias': 0.42,
  'source': 'seed-market',
  'trend_score': 0.51,
  'volatility': 0.064,
  'volume_24h': 4980000000.0},
 {'as_of': '2026-04-06T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.032,
  'price': 130.0,
  'signal_bias': 0.55,
  'source': 'seed-market',
  'trend_score': 0.6,
  'volatility': 0.067,
  'volume_24h': 5140000000.0},
 {'as_of': '2026-04-07T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.023,
  'price': 133.0,
  'signal_bias': 0.58,
  'source': 'seed-market',
  'trend_score': 0.63,
  'volatility': 0.065,
  'volume_24h': 5220000000.0},
 {'as_of': '2026-04-08T00:00:00Z',
  'asset': 'SOL',
  'change_24h': 0.023,
  'price': 136.0,
  'signal_bias': 0.6,
  'source': 'seed-market',
  'trend_score': 0.66,
  'volatility': 0.064,
  'volume_24h': 5360000000.0}]

SIGNAL_SEEDS = [{'asset': 'BTC',
  'author_handle': '@seedflowdesk',
  'channel': 'social',
  'engagement_score': 0.763,
  'external_id': 'sig-x-btc-0404',
  'ingest_batch_id': 'seed-20260404',
  'observed_at': '2026-04-04T10:15:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.82,
  'sentiment': 0.46,
  'source': 'X',
  'source_type': 'social',
  'summary': 'Institutional commentary pointed to steady demand returning after a risk-off dip.',
  'title': 'ETF desks report stronger spot demand',
  'url': 'https://example.com/x/btc-0404'},
 {'asset': 'ETH',
  'author_handle': 'u/seedresearch',
  'channel': 'social',
  'engagement_score': 0.725,
  'external_id': 'sig-reddit-eth-0405',
  'ingest_batch_id': 'seed-20260405',
  'observed_at': '2026-04-05T09:45:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.78,
  'sentiment': 0.52,
  'source': 'Reddit',
  'source_type': 'social',
  'summary': 'Retail discussion shifted positive as users framed the upgrade as a catalyst for flows.',
  'title': 'Developers expect follow-through after staking update',
  'url': 'https://example.com/reddit/eth-0405'},
 {'asset': 'BTC',
  'author_handle': 'marketwire-desk',
  'channel': 'news',
  'engagement_score': None,
  'external_id': 'sig-news-btc-0405',
  'ingest_batch_id': 'seed-20260405',
  'observed_at': '2026-04-05T12:30:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.81,
  'sentiment': 0.44,
  'source': 'MarketWire',
  'source_type': 'news',
  'summary': 'A cluster of desks noted friendlier liquidity conditions after a week of defensive positioning.',
  'title': 'Macro desks see improving liquidity tone',
  'url': 'https://example.com/news/btc-0405'},
 {'asset': 'SOL',
  'author_handle': 'chainwatch-desk',
  'channel': 'news',
  'engagement_score': None,
  'external_id': 'sig-news-sol-0406',
  'ingest_batch_id': 'seed-20260406',
  'observed_at': '2026-04-06T08:20:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.76,
  'sentiment': 0.61,
  'source': 'ChainWatch',
  'source_type': 'news',
  'summary': 'Activity accelerated across key apps, feeding a higher-beta narrative around SOL.',
  'title': 'On-chain activity expands with renewed memecoin velocity',
  'url': 'https://example.com/news/sol-0406'},
 {'asset': 'SOL',
  'author_handle': '@seedflowdesk',
  'channel': 'social',
  'engagement_score': 0.8,
  'external_id': 'sig-x-sol-0406',
  'ingest_batch_id': 'seed-20260406',
  'observed_at': '2026-04-06T11:05:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.86,
  'sentiment': 0.74,
  'source': 'X',
  'source_type': 'social',
  'summary': 'Public trader chatter accelerated while price held above a key breakout area.',
  'title': 'High-engagement traders call for breakout continuation',
  'url': 'https://example.com/x/sol-0406'},
 {'asset': 'ETH',
  'author_handle': 'macrolens-desk',
  'channel': 'news',
  'engagement_score': None,
  'external_id': 'sig-news-eth-0406',
  'ingest_batch_id': 'seed-20260406',
  'observed_at': '2026-04-06T13:00:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.73,
  'sentiment': 0.41,
  'source': 'MacroLens',
  'source_type': 'news',
  'summary': 'The market narrative improved as previously defensive positioning normalized.',
  'title': 'Flows stabilize around ETH after weak positioning washout',
  'url': 'https://example.com/news/eth-0406'},
 {'asset': 'BTC',
  'author_handle': 'u/seedresearch',
  'channel': 'social',
  'engagement_score': 0.642,
  'external_id': 'sig-reddit-btc-0407',
  'ingest_batch_id': 'seed-20260407',
  'observed_at': '2026-04-07T08:50:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.69,
  'sentiment': 0.57,
  'source': 'Reddit',
  'source_type': 'social',
  'summary': 'Retail sentiment turned sharply more constructive after BTC reclaimed the prior weekly range.',
  'title': 'Community sentiment flips risk-on after range reclaim',
  'url': 'https://example.com/reddit/btc-0407'},
 {'asset': 'BTC',
  'author_handle': 'policywatch-desk',
  'channel': 'macro',
  'engagement_score': None,
  'external_id': 'sig-news-btc-0407',
  'ingest_batch_id': 'seed-20260407',
  'observed_at': '2026-04-07T14:10:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.84,
  'sentiment': 0.36,
  'source': 'PolicyWatch',
  'source_type': 'macro',
  'summary': 'Macro commentary reduced near-term stress expectations and supported higher-beta positioning.',
  'title': 'Policy commentary lowers immediate volatility fears',
  'url': 'https://example.com/macro/btc-0407'},
 {'asset': 'ETH',
  'author_handle': '@seedflowdesk',
  'channel': 'social',
  'engagement_score': 0.735,
  'external_id': 'sig-x-eth-0408',
  'ingest_batch_id': 'seed-20260408',
  'observed_at': '2026-04-08T07:25:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.79,
  'sentiment': 0.63,
  'source': 'X',
  'source_type': 'social',
  'summary': 'A high-signal subset of traders framed ETH as a cleaner continuation setup than BTC.',
  'title': 'ETH trader clusters lean for continuation',
  'url': 'https://example.com/x/eth-0408'},
 {'asset': 'SOL',
  'author_handle': 'exchangeflow-desk',
  'channel': 'news',
  'engagement_score': None,
  'external_id': 'sig-news-sol-0408',
  'ingest_batch_id': 'seed-20260408',
  'observed_at': '2026-04-08T09:05:00Z',
  'provider_name': 'seed-provider',
  'relevance': 0.72,
  'sentiment': 0.58,
  'source': 'ExchangeFlow',
  'source_type': 'news',
  'summary': 'Desk commentary emphasized SOL leadership as market breadth improved.',
  'title': 'SOL continues to lead high-beta beta basket',
  'url': 'https://example.com/news/sol-0408'}]

PREDICTION_SEEDS = [{'asset': 'BTC',
  'bot_slug': 'macro-narrative',
  'confidence': 0.69,
  'direction': 'bullish',
  'horizon_days': 7,
  'horizon_label': '7 days',
  'invalidation': 'Sustained break back into the prior downside range.',
  'published_at': '2026-04-01T08:00:00Z',
  'source_signal_ids': '[1,3]',
  'status': 'pending',
  'thesis': 'Liquidity tone and ETF stabilization support a higher medium-term base.',
  'trigger_conditions': 'Hold above the reclaimed weekly range.'},
 {'asset': 'ETH',
  'bot_slug': 'macro-narrative',
  'confidence': 0.63,
  'direction': 'bullish',
  'horizon_days': 7,
  'horizon_label': '7 days',
  'invalidation': 'Renewed risk-off positioning across majors.',
  'published_at': '2026-04-01T10:00:00Z',
  'source_signal_ids': '[2,6]',
  'status': 'pending',
  'thesis': 'Improving risk appetite and cleaner flow backdrop support ETH catch-up.',
  'trigger_conditions': 'Continued closes above the early-week reclaim.'},
 {'asset': 'ETH',
  'bot_slug': 'social-momentum',
  'confidence': 0.74,
  'direction': 'bullish',
  'horizon_days': 3,
  'horizon_label': '3 days',
  'invalidation': 'Momentum stalls on expanding sell volume.',
  'published_at': '2026-04-05T09:30:00Z',
  'source_signal_ids': '[2,9]',
  'status': 'pending',
  'thesis': 'Social acceleration and cleaner structure point to a short continuation window.',
  'trigger_conditions': 'Spot remains above the most recent breakout shelf.'},
 {'asset': 'SOL',
  'bot_slug': 'social-momentum',
  'confidence': 0.77,
  'direction': 'bullish',
  'horizon_days': 3,
  'horizon_label': '3 days',
  'invalidation': 'Narrative loses traction during the first retest.',
  'published_at': '2026-04-05T10:10:00Z',
  'source_signal_ids': '[4,5,10]',
  'status': 'pending',
  'thesis': 'High-signal trader chatter aligns with accelerating participation across the ecosystem.',
  'trigger_conditions': 'Hold above breakout with social engagement still rising.'},
 {'asset': 'SOL',
  'bot_slug': 'breakout',
  'confidence': 0.71,
  'direction': 'bullish',
  'horizon_days': 1,
  'horizon_label': '1 day',
  'invalidation': 'Immediate re-entry into the prior range.',
  'published_at': '2026-04-07T08:00:00Z',
  'source_signal_ids': '[5,10]',
  'status': 'pending',
  'thesis': 'Range expansion and volume confirmation favor another short impulse leg.',
  'trigger_conditions': 'Price holds the breakout level into the next session.'},
 {'asset': 'BTC',
  'bot_slug': 'breakout',
  'confidence': 0.58,
  'direction': 'bearish',
  'horizon_days': 1,
  'horizon_label': '1 day',
  'invalidation': 'Immediate reclaim with trend strength intact.',
  'published_at': '2026-04-06T11:45:00Z',
  'source_signal_ids': '[7,8]',
  'status': 'pending',
  'thesis': 'Momentum looked extended after a fast move and intraday continuation risked exhaustion.',
  'trigger_conditions': 'Loss of intraday support on heavy volume.'},
 {'asset': 'SOL',
  'bot_slug': 'contrarian',
  'confidence': 0.66,
  'direction': 'bearish',
  'horizon_days': 3,
  'horizon_label': '3 days',
  'invalidation': 'Fresh impulse closes above the prior extension high.',
  'published_at': '2026-04-04T15:30:00Z',
  'source_signal_ids': '[4,5]',
  'status': 'pending',
  'thesis': 'Narrative enthusiasm appeared crowded enough to invite a sharp but temporary reset.',
  'trigger_conditions': 'Crowd participation remains one-sided while price stalls.'},
 {'asset': 'BTC',
  'bot_slug': 'contrarian',
  'confidence': 0.61,
  'direction': 'bullish',
  'horizon_days': 3,
  'horizon_label': '3 days',
  'invalidation': 'Fresh breakdown on broad risk-off pressure.',
  'published_at': '2026-04-04T13:40:00Z',
  'source_signal_ids': '[1,3]',
  'status': 'pending',
  'thesis': 'The pullback looked emotional rather than structural, creating a reversion setup.',
  'trigger_conditions': 'Buyers defend the retracement shelf within one session.'},
 {'asset': 'BTC',
  'bot_slug': 'risk-sentinel',
  'confidence': 0.57,
  'direction': 'bearish',
  'horizon_days': 3,
  'horizon_label': '3 days',
  'invalidation': 'Risk compresses while price keeps grinding higher.',
  'published_at': '2026-04-02T12:00:00Z',
  'source_signal_ids': '[1,8]',
  'status': 'pending',
  'thesis': 'Short-term risk looked underpriced versus positioning after the early-week bounce.',
  'trigger_conditions': 'Volatility expansion arrives before breadth improves.'},
 {'asset': 'ETH',
  'bot_slug': 'risk-sentinel',
  'confidence': 0.62,
  'direction': 'neutral',
  'horizon_days': 1,
  'horizon_label': '1 day',
  'invalidation': 'Directional expansion exceeds the expected range.',
  'published_at': '2026-04-06T16:00:00Z',
  'source_signal_ids': '[6,9]',
  'status': 'pending',
  'thesis': 'Event risk looked balanced with no clear edge beyond short-term chop.',
  'trigger_conditions': 'Volatility stays contained after the event window.'},
 {'asset': 'ETH',
  'bot_slug': 'news-reaction',
  'confidence': 0.67,
  'direction': 'bullish',
  'horizon_days': 1,
  'horizon_label': '1 day',
  'invalidation': 'News fades immediately with no spot participation.',
  'published_at': '2026-04-06T10:30:00Z',
  'source_signal_ids': '[6,9]',
  'status': 'pending',
  'thesis': 'The market still had room to reprice supportive ETH flow headlines.',
  'trigger_conditions': 'Follow-through buyers appear into the next liquid session.'},
 {'asset': 'SOL',
  'bot_slug': 'news-reaction',
  'confidence': 0.59,
  'direction': 'bearish',
  'horizon_days': 1,
  'horizon_label': '1 day',
  'invalidation': 'Fresh buyers keep paying through the headline impulse.',
  'published_at': '2026-04-06T09:00:00Z',
  'source_signal_ids': '[4,10]',
  'status': 'pending',
  'thesis': 'The first wave of good news felt fully priced and vulnerable to mean reversion.',
  'trigger_conditions': 'Price rejects the first continuation attempt.'}]

USER_SEEDS = [{'created_at': '2026-04-01T08:00:00Z',
  'display_name': 'Demo Operator',
  'email': 'demo@botsocietymarkets.local',
  'is_demo_user': True,
  'slug': 'demo-operator',
  'tier': 'enterprise-preview'}]

FOLLOW_SEEDS = [{'bot_slug': 'macro-narrative', 'created_at': '2026-04-01T09:00:00Z', 'user_slug': 'demo-operator'},
 {'bot_slug': 'social-momentum', 'created_at': '2026-04-01T09:05:00Z', 'user_slug': 'demo-operator'}]

WATCHLIST_SEEDS = [{'asset': 'BTC', 'created_at': '2026-04-01T09:15:00Z', 'user_slug': 'demo-operator'},
 {'asset': 'ETH', 'created_at': '2026-04-01T09:16:00Z', 'user_slug': 'demo-operator'},
 {'asset': 'SOL', 'created_at': '2026-04-01T09:17:00Z', 'user_slug': 'demo-operator'}]

ALERT_RULE_SEEDS = [{'asset': None, 'bot_slug': 'macro-narrative', 'created_at': '2026-04-01T09:20:00Z', 'is_active': 1, 'min_confidence': 0.62, 'user_slug': 'demo-operator'},
 {'asset': 'SOL', 'bot_slug': None, 'created_at': '2026-04-01T09:25:00Z', 'is_active': 1, 'min_confidence': 0.68, 'user_slug': 'demo-operator'}]
